[project]
name = "nameclaim"
description = "Unique voting contract for project 05"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.nameclaim]
path = "contracts/nameclaim.clar"

[repl.analysis]
passes = ["check_checker"]
